### ISSUE TITLE
Consider releasing 1.0.0

### ISSUE THREAD

**Issue by npmccallum** [AerialX/const-default.rs#7]
Because of the way semver works when the version is `<1.0.0`, every release of `const-default` is consider an API breaking release. However, this crate hasn't actually broken API. In fact, it has been relatively stable; adding only new features or fixes in all the releases since `0.1.0`.

Having a version `<1.0.0` currently causes a burden on consumers of this crate because it means that for every release of `const-default`, the entire dependency chain has to be updated otherwise cargo thinks the traits are different. This would be solved by simply releasing `1.0.0` and bumping `1.x.y` for every release.

You can always still make a breaking change by releasing `2.x.y`. It would just be nice to not have to rebase my entire dependency chain on every release unnecessarily.

**Comment by AerialX** [comment]
> Because of the way semver works when the version is <1.0.0, every release of const-default is consider an API breaking release. However, this crate hasn't actually broken API. In fact, it has been relatively stable; adding only new features or fixes in all the releases since 0.1.0.

This isn't really specific to 0.x.y, since the minor y version is incremented for compatible releases. The major version x changes were made intentionally due to MSRV and other changes.

That aside, I agree that aiming for a stable 1.0.0 would be reasonable. The API is very simple, and support for later rust versions can still be added in a backward-compatible way via cfgs and build scripts and things.
